current_version: 0.1.12
replaces:
- file: back/Cargo.toml
  pattern: ^version\s*=\s*\"{{current_version}}\"$
- file: front/.env
  pattern: ^VITE_VERSION={{current_version}}$
- file: front/.env.development
  pattern: ^VITE_VERSION={{current_version}}$
