CREATE TABLE IF NOT EXISTS posts (
    id SERIAL PRIMARY KEY,
    tag VARCHAR NOT NULL UNIQUE,
    slug VARCHAR NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
);

